version: '3.5'
services:
  django:
      build:
        context: .
      container_name: django
      command: >
        sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:3003"
      ports:
        - "8040:3003"
      volumes:
          - ./app:/app
      environment:
        - DB_HOST=postgres
        - DB_NAME=django
        - DB_USER=django
        - DB_PASS=password
      restart: always
      depends_on:
          - postgres

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=django
    volumes:
       - postgres_data:/var/lib/postgresql/data/
    restart: always
volumes:
  postgres_data:

